import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { verifyAdminRequest, handleAdminError } from '@/lib/api-auth';
import {
  generateAssignedEmail,
  isEmailUsingDomain,
  resolveAssignedEmailDomain,
} from '@/lib/email-utils';
import { deleteWebhookLogStorageFiles } from '@/lib/inbound-processing';
import { getUtcMonthKey } from '@/lib/credits';

const IN_QUERY_LIMIT = 30;
const MAX_ASSIGNED_EMAIL_ATTEMPTS = 10;
/** Maximum number of log IDs processed concurrently when deleting storage artifacts. */
const STORAGE_DELETE_CONCURRENCY = 20;

/** UUID v4 pattern — IDs generated by crypto.randomUUID() always match this. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Validates that all elements of an array are well-formed UUIDs.
 * This guards the JSONB OR query below against injection when IDs are interpolated
 * into the filter string.
 */
function assertUuids(ids: string[]): void {
  for (const id of ids) {
    if (!UUID_RE.test(id)) {
      throw new Error(`Invalid ID format: ${id}`);
    }
  }
}

async function deleteUserStorageArtifacts(logIds: string[]): Promise<void> {
  if (logIds.length === 0) return;

  try {
    const supabase = createAdminClient();

    for (let i = 0; i < logIds.length; i += STORAGE_DELETE_CONCURRENCY) {
      const batch = logIds.slice(i, i + STORAGE_DELETE_CONCURRENCY);
      await Promise.all(
        batch.flatMap((logId) =>
          [`${logId}/`].map(async (prefix) => {
            const { data: files } = await supabase.storage
              .from('email-attachments')
              .list(prefix, { limit: 1000 });
            if (files && files.length > 0) {
              const paths = files.map((f) => `${prefix}${f.name}`);
              await supabase.storage.from('email-attachments').remove(paths);
            }
          }),
        ),
      );
    }
  } catch (error) {
    console.error('[admin/users/[uid]] failed to delete storage artifacts:', error);
  }
}

async function collectUserDataIds(uid: string): Promise<{
  logIds: string[];
  jobIds: string[];
  webhookLogIds: string[];
  mergeIds: string[];
  mergeSuggestionIds: string[];
  ruleIds: string[];
}> {
  const supabase = createAdminClient();

  const [rulesResult, logsResult, mergesResult, suggestionsResult, jobsResult] = await Promise.all([
    supabase.from('rules').select('id').eq('user_id', uid),
    supabase.from('email_logs').select('id').eq('user_id', uid),
    supabase.from('entity_merges').select('id').eq('user_id', uid),
    supabase.from('entity_merge_suggestions').select('id').eq('user_id', uid),
    supabase.from('email_jobs').select('id').filter('payload->>userId', 'eq', uid),
  ]);

  const logIds = (logsResult.data ?? []).map((d) => d.id as string);
  const jobIds = (jobsResult.data ?? []).map((d) => d.id as string);

  // Collect webhook log IDs referencing this user's email logs or jobs
  const webhookLogIds: string[] = [];
  const chunks: string[][] = [];
  const allRefIds = [...logIds, ...jobIds];
  for (let i = 0; i < allRefIds.length; i += IN_QUERY_LIMIT) {
    chunks.push(allRefIds.slice(i, i + IN_QUERY_LIMIT));
  }
  for (const chunk of chunks) {
    assertUuids(chunk);
    const { data: wRows } = await supabase
      .from('mailgun_webhook_logs')
      .select('id')
      .or(
        `linked->>emailLogId.in.(${chunk.map((id) => `"${id}"`).join(',')}),linked->>jobId.in.(${chunk.map((id) => `"${id}"`).join(',')})`,
      );
    if (wRows) webhookLogIds.push(...wRows.map((r) => r.id as string));
  }

  return {
    logIds,
    jobIds,
    webhookLogIds,
    mergeIds: (mergesResult.data ?? []).map((d) => d.id as string),
    mergeSuggestionIds: (suggestionsResult.data ?? []).map((d) => d.id as string),
    ruleIds: (rulesResult.data ?? []).map((d) => d.id as string),
  };
}

async function deleteAllUserData(uid: string): Promise<{ logIds: string[] }> {
  const { logIds, jobIds, webhookLogIds, mergeIds, mergeSuggestionIds, ruleIds } =
    await collectUserDataIds(uid);

  await deleteUserStorageArtifacts(logIds);
  await deleteWebhookLogStorageFiles(webhookLogIds);

  const supabase = createAdminClient();

  // Delete in dependency order
  await Promise.all([
    ruleIds.length > 0 ? supabase.from('rules').delete().in('id', ruleIds) : Promise.resolve(),
    mergeIds.length > 0
      ? supabase.from('entity_merges').delete().in('id', mergeIds)
      : Promise.resolve(),
    mergeSuggestionIds.length > 0
      ? supabase.from('entity_merge_suggestions').delete().in('id', mergeSuggestionIds)
      : Promise.resolve(),
    jobIds.length > 0 ? supabase.from('email_jobs').delete().in('id', jobIds) : Promise.resolve(),
    webhookLogIds.length > 0
      ? supabase.from('mailgun_webhook_logs').delete().in('id', webhookLogIds)
      : Promise.resolve(),
    logIds.length > 0 ? supabase.from('email_logs').delete().in('id', logIds) : Promise.resolve(),
    supabase.from('entity_relations').delete().eq('user_id', uid),
    supabase.from('entity_flows').delete().eq('user_id', uid),
    supabase.from('entity_place_maps').delete().eq('user_id', uid),
    supabase.from('user_memory').delete().eq('user_id', uid),
  ]);

  return { logIds };
}

async function provisionFreshUserProfile(uid: string, currentUserData: Record<string, unknown>) {
  const supabase = createAdminClient();
  const { data: settingsRow } = await supabase
    .from('settings')
    .select('data')
    .eq('id', 'global')
    .single();
  const settings = settingsRow?.data as Record<string, unknown> | undefined;
  const assignedDomain = resolveAssignedEmailDomain(settings);

  let authEmail = typeof currentUserData.email === 'string' ? currentUserData.email : '';
  let authDisplayName =
    typeof currentUserData.display_name === 'string' ? currentUserData.display_name.trim() : '';
  let isActive = currentUserData.is_active === true;

  try {
    const { data: authData } = await supabase.auth.admin.getUserById(uid);
    if (authData?.user) {
      authEmail = authData.user.email ?? authEmail;
      authDisplayName =
        (authData.user.user_metadata?.display_name as string | undefined)?.trim() ??
        authDisplayName;
      isActive = !!authData.user.email_confirmed_at;
    }
  } catch (error) {
    // If user not found in auth, continue with existing data
    console.warn(`Could not fetch auth user ${uid}:`, error);
  }

  if (authEmail && isEmailUsingDomain(authEmail, assignedDomain)) {
    throw new Error("Can't reset an account that uses the managed inbound domain");
  }

  let assignedEmail = '';
  for (let attempt = 0; attempt < MAX_ASSIGNED_EMAIL_ATTEMPTS; attempt++) {
    const candidate = generateAssignedEmail(assignedDomain);
    const { data: existing } = await supabase
      .from('users')
      .select('id')
      .eq('assigned_email', candidate)
      .limit(1);
    if (!existing || existing.length === 0) {
      assignedEmail = candidate;
      break;
    }
  }

  if (!assignedEmail) {
    throw new Error('Failed to provision assigned email');
  }

  await supabase.from('users').upsert({
    id: uid,
    email: authEmail,
    assigned_email: assignedEmail,
    created_at: new Date().toISOString(),
    is_admin: false,
    is_active: isActive,
    suspended: false,
    credits_usage_month: getUtcMonthKey(),
    monthly_credits_used: 0,
    monthly_credits_bonus: 0,
    credits_threshold_notified: false,
    analysis_output_language: 'en',
    ...(authDisplayName ? { display_name: authDisplayName } : {}),
  });
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ uid: string }> },
) {
  try {
    await verifyAdminRequest(request);
    const updates = await request.json();
    const { uid } = await params;
    const supabase = createAdminClient();

    const allowed = ['isAdmin', 'isActive'];
    const filtered = Object.fromEntries(
      Object.entries(updates).filter(([k]) => allowed.includes(k)),
    );

    // Map camelCase to snake_case for DB
    const dbUpdates: { is_admin?: boolean; is_active?: boolean; suspended?: boolean } = {};
    if ('isAdmin' in filtered) dbUpdates.is_admin = Boolean(filtered.isAdmin);
    if ('isActive' in filtered) {
      const { data: targetRow } = await supabase
        .from('users')
        .select('is_admin')
        .eq('id', uid)
        .single();
      if (targetRow?.is_admin) {
        return NextResponse.json({ error: 'Cannot suspend an admin user' }, { status: 400 });
      }
      dbUpdates.is_active = Boolean(filtered.isActive);
      dbUpdates.suspended = !filtered.isActive;
    }

    await supabase.from('users').update(dbUpdates).eq('id', uid);
    return NextResponse.json({ success: true });
  } catch (error) {
    return handleAdminError(error, 'admin/users/[uid] PATCH');
  }
}

export async function POST(request: NextRequest, { params }: { params: Promise<{ uid: string }> }) {
  try {
    await verifyAdminRequest(request);
    const { uid } = await params;
    const supabase = createAdminClient();

    const { data: targetRow } = await supabase
      .from('users')
      .select('is_admin, email, display_name, is_active')
      .eq('id', uid)
      .single();
    if (!targetRow) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }
    if (targetRow.is_admin) {
      return NextResponse.json({ error: 'Cannot reset an admin user' }, { status: 400 });
    }

    await deleteAllUserData(uid);
    await provisionFreshUserProfile(uid, targetRow as Record<string, unknown>);

    return NextResponse.json({ success: true });
  } catch (error) {
    return handleAdminError(error, 'admin/users/[uid] POST');
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ uid: string }> },
) {
  try {
    await verifyAdminRequest(request);
    const { uid } = await params;
    const supabase = createAdminClient();

    const { data: targetRow } = await supabase
      .from('users')
      .select('is_admin')
      .eq('id', uid)
      .single();
    if (!targetRow) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }
    if (targetRow.is_admin) {
      return NextResponse.json({ error: 'Cannot delete an admin user' }, { status: 400 });
    }

    await deleteAllUserData(uid);

    // Delete the users row first (FK constraint)
    await supabase.from('users').delete().eq('id', uid);

    // Delete Supabase Auth user
    const { error: authError } = await supabase.auth.admin.deleteUser(uid);
    if (authError && !authError.message.includes('not found')) {
      console.error(`Failed to delete Supabase Auth user ${uid}:`, authError);
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    return handleAdminError(error, 'admin/users/[uid] DELETE');
  }
}
